//-----------------------------------------------------------------------
//Lynx code generated by c++
//-----------------------------------------------------------------------

using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using System.Runtime.InteropServices;
[ExecuteInEditMode]
public class TableManager : Singleton<TableManager>, IManagerBase
{
    public const string GroupName = "tables";
    Dictionary<string, LitJson.JsonData> mTableMap = new Dictionary<string, LitJson.JsonData>();


    public void Initial()
    {
        ResourceManager.GetSingleton().LoadAssetBundle(GroupName);
    }
    public void Release()
    {
        ResourceManager.GetSingleton().ReleaseAssetBundle(GroupName);
    }
    public LitJson.JsonData GetTable(string tableName)
    {
        LitJson.JsonData jd = null;

        if (!mTableMap.TryGetValue(tableName.ToLower(), out jd))
        {
            TextAsset table = ResourceManager.GetSingleton().CreateResource<TextAsset>(tableName, GroupName);
            jd = LitJson.JsonMapper.ToObject(table.text);

            mTableMap.Add(tableName.ToLower(), jd);
            return jd;
        }
        return jd;
    }
    public LitJson.JsonData GetSheet(string tableName, string sheetName)
    {
        LitJson.JsonData jd = GetTable(tableName);
        if (jd == null) return null;

        return jd[sheetName];
    }


}
